(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> define_table argument is not a Field or Table: reference userio"
p3
sS'layer'
p4
S'C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\applications\\welcome\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 099238D8, file "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\applications\\welcome\\models\\db.py", line 8>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\applications\\welcome\\models\\db.py", line 102, in <module>\n    auth.define_tables(username=True, signature=False)\n  File "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\gluon\\tools.py", line 2216, in define_tables\n    super(Auth, self).define_tables(username, signature, migrate, fake_migrate)._table_signature_list\n  File "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\gluon\\authapi.py", line 320, in define_tables\n    format=\'%(username)s\'))\n  File "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 587, in define_table\n    table = self.lazy_define_table(tablename, *fields, **args)\n  File "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 599, in lazy_define_table\n    table = table_class(self, tablename, *fields, **args)\n  File "C:\\Users\\asus\\Downloads\\web2py_win\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 306, in __init__\n    field\nSyntaxError: define_table argument is not a Field or Table: reference userio\n'
p11
s.